// Automatically generated, do not modify directly.
// Generated by MicroBuild.

#include "Version.h"

const char* VersionInfo::DAY = "3";
const char* VersionInfo::MONTH = "8";
const char* VersionInfo::YEAR = "2016";
const char* VersionInfo::HOUR = "22";
const char* VersionInfo::MINUTE = "9";
const char* VersionInfo::SECOND = "45";
const char* VersionInfo::CHANGELIST = "d286d23";
const char* VersionInfo::FULLVERSION_STRING = "d286d23";
const long VersionInfo::TOTAL_CHANGELISTS = 2;
