// Automatically generated, do not modify directly.
// Generated by MicroBuild.

#pragma once

class VersionInfo
{
public:
	static const char* DAY;
	static const char* MONTH;
	static const char* YEAR;
	static const char* HOUR;
	static const char* MINUTE;
	static const char* SECOND;
	static const char* CHANGELIST;
	static const char* FULLVERSION_STRING;
	static const long TOTAL_CHANGELISTS;
};
